kind: pipeline
name: default

steps:
  - name: db-migrations
    image: golang
    commands:
      - sleep 25
      - go mod download
      - cd ../ && go get github.com/go-bindata/go-bindata/...
      - cd src && make migrate-all
services:
  - name: mysql
    image: mysql:8
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: powerdoc
  - name: postgres
    image: postgres:10-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: powerdoc