// Package migrations Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// 1_create_users_table.down.sql
// 1_create_users_table.up.sql
package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __1_create_users_tableDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2d\x4e\x2d\x2a\xb6\xe6\x02\x04\x00\x00\xff\xff\x2c\x02\x3d\xa7\x1c\x00\x00\x00")

func _1_create_users_tableDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1_create_users_tableDownSql,
		"1_create_users_table.down.sql",
	)
}

func _1_create_users_tableDownSql() (*asset, error) {
	bytes, err := _1_create_users_tableDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1_create_users_table.down.sql", size: 28, mode: os.FileMode(420), modTime: time.Unix(1592299585, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1_create_users_tableUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xd0\x4f\x4b\xc3\x40\x10\x05\xf0\x7b\x3e\xc5\xf3\x96\x14\xa1\x09\xea\xa9\xa7\xd8\x8e\x12\x4c\x57\x59\x36\x60\x4f\xcb\xd2\x1d\xea\x42\xfe\xc8\xee\x16\xfd\xf8\x22\x69\x8d\xd1\xce\x71\x7e\x33\xef\xf0\xd6\x92\x4a\x45\x50\xe5\x7d\x4d\x38\x06\xf6\x21\x49\x13\x00\x38\x3a\x8b\xf9\x54\x42\xd1\x23\x49\xbc\xc8\x6a\x5b\xca\x1d\x9e\x68\x87\xe5\xe2\xea\x36\x2f\xf2\x02\x65\xa3\x9e\x75\x25\xd6\x92\xb6\x24\x14\x16\xcb\xeb\x31\x25\xb0\xef\x4d\xc7\x53\xca\xfe\xcd\xf8\xf4\x2e\xcf\x46\x7f\x37\x21\x7c\x0c\xde\xfe\xf1\x22\x3f\x1f\xcc\x9f\x7f\x0e\x6e\xce\xce\x9d\x71\xed\x7f\x9f\x02\x5a\x13\xa2\x6e\x87\xc3\x81\xad\x76\xbd\x36\x11\xd6\x44\x8e\xae\xe3\xd1\xf7\x9e\x4d\x64\xfb\x0d\xa7\x99\xbb\xe5\x96\x2f\x3b\x36\xf4\x50\x36\xb5\x82\x68\xea\x3a\xc9\x56\xc9\xa9\xcb\x4a\x6c\xe8\x15\xce\x7e\xea\x5f\xbf\x43\x3f\xb6\x8b\x74\x5a\x66\xab\xaf\x00\x00\x00\xff\xff\xe9\xcd\xff\x7c\x7e\x01\x00\x00")

func _1_create_users_tableUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1_create_users_tableUpSql,
		"1_create_users_table.up.sql",
	)
}

func _1_create_users_tableUpSql() (*asset, error) {
	bytes, err := _1_create_users_tableUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1_create_users_table.up.sql", size: 382, mode: os.FileMode(420), modTime: time.Unix(1592298160, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"1_create_users_table.down.sql": _1_create_users_tableDownSql,
	"1_create_users_table.up.sql":   _1_create_users_tableUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"1_create_users_table.down.sql": &bintree{_1_create_users_tableDownSql, map[string]*bintree{}},
	"1_create_users_table.up.sql":   &bintree{_1_create_users_tableUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
